### ISSUE TITLE
figure title not centered in default template (`:plotly`)

### ISSUE THREAD

**Issue by disberd** [sglyon/PlotlyBase.jl#64]
Hi, 
Thanks for the massive rate of updates in the last weeks.
I noticed that the default template in the new template system is the only one where the title of the figure is not centered by default but is put on the left.
The template has in fact a field `title: {x : 0.05}`.
Is this the intended behavior or is it a mistake?

**Comment by thchr** [comment]
For posterity's sake, I'll just note that this is basically the same as #63 (and also as https://github.com/JuliaPlots/PlotlyJS.jl/issues/405), i.e. tied to the changing of the default template in PlotlyBase 0.8.2.

**Comment by sglyon** [comment]
Hi @disberd  thanks for opening.

This was an intentional decision to match the plotting style generated by plotly's python and R packages. 

This should (hopefully!) be the last set of breaking changes for the foreseeable future. We are nearing a 1.0 release and things will settle down and be stable at that time. 

Thanks @thchr for linking the issues! 

- - -

I'm going to close here as I don't think there are any bugs or things to resolve/change. If you have further questions, please don't hesitate to reach out!
