### ISSUE TITLE
savefig() for saving .png is not working with plotly() backend in Plots.jl

### ISSUE THREAD

**Issue by lambcount** [sglyon/PlotlyBase.jl#82]
It seems like that the savefig function is not working anymore for the newest Plots version.

When using the plotly backend in Plots, this Info appears: "For saving to png with the Plotly backend PlotlyBase has to be installed."

After installing PlotlyBase, i am still not able to save a plot with the plotly backend as an .pdf, .png or .svg file. Only .json and .html seems to work. Currently i am using Julia 1.6.2 with the following enviroment. Iam sure it was working with older versions, so it should be a bug. For the gr backend it is also working, but i need it to work with the plotly backend as well.

```
(User) pkg> st
      Status `~/Documents/Project.toml`
  [a03496cd] PlotlyBase v0.8.15
  [91a5bcdd] Plots v1.21.2

```

An example of the code and the error message is given below.

```
julia> using Plots

julia> plotly()
Plots.PlotlyBackend()

julia> p = plot(collect(1:100))

julia> savefig(p,"./tmp.png")
ERROR: UndefVarError: savefig not defined
Stacktrace:
 [1] _show(io::IOStream, #unused#::MIME{Symbol("image/png")}, plt::Plots.Plot{Plots.PlotlyBackend})
   @ Plots ~/.julia/packages/Plots/WBKlv/src/backends/plotlybase.jl:21
 [2] show
   @ ~/.julia/packages/Plots/WBKlv/src/output.jl:213 [inlined]
 [3] png(plt::Plots.Plot{Plots.PlotlyBackend}, fn::String)
   @ Plots ~/.julia/packages/Plots/WBKlv/src/output.jl:7
 [4] savefig(plt::Plots.Plot{Plots.PlotlyBackend}, fn::String)
   @ Plots ~/.julia/packages/Plots/WBKlv/src/output.jl:123
 [5] top-level scope
   @ REPL[23]:1
```

**Comment by disberd** [comment]
PlotlyBase went a quite significant overhaul during the summer and the `savefig` function was moved from PlotlyBase to PlotlyJS with this PR https://github.com/sglyon/PlotlyBase.jl/pull/58

The code at https://github.com/JuliaPlots/Plots.jl/blob/a65cda8b7e77a9b6031c912b27f73c38903d4175/src/backends/plotlybase.jl#L21-L23 is then probably outdated since it's calling savefig directly from PlotyBase (where it's not anymore).

if you were to use `plotlyjs()` instead of `plotly()` it should work (see, https://github.com/JuliaPlots/PlotDocs.jl/pull/253).

So I think the issue might be more related to the Plots repo than here?

**Comment by sglyon** [comment]
Good catch @disberd -- I think you are right. I'll close here and ask that if anyone is still having problems with this via Plots.jl that an issue be opened up over in Plots.jl
